name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: SimpleJava/javapp
          registry: ghcr.io
          githubOrg: override-org # optional
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }} 
